### ISSUE TITLE
UI/UX refinements

### ISSUE THREAD

**Issue by GroovinChip** [jhu-digital-manuscripts/AnIOp#101]
Per a conversation @jabrah and I had this afternoon, we determined the below UI/UX refinements would be good for me to work on. I will check these off as they are completed. 
- [x] [Try to overlay Pleiades link in the map itself for better UX](https://github.com/jhu-digital-manuscripts/rosademo-frontend/issues/17)
- [x] [Show tags as chips](https://github.com/jhu-digital-manuscripts/rosademo-frontend/issues/18)
- [ ] [Consider not showing 'creator'](https://github.com/jhu-digital-manuscripts/rosademo-frontend/issues/19)
- [ ] [Set accent colors for dark theme for better visibility](https://github.com/jhu-digital-manuscripts/rosademo-frontend/issues/20)
- [ ] [Try to improve dark theme overall](https://github.com/jhu-digital-manuscripts/rosademo-frontend/issues/21)
- [ ] [Think about display options for annotation label and annotation comment](https://github.com/jhu-digital-manuscripts/rosademo-frontend/issues/22)

**Comment by GroovinChip** [comment]
Just had a call with @jabrah, it appears that for now only the tickets related to theming are relevant to work on at the moment.
